package com.equipo10.projectointegrador.model;

import com.equipo10.projectointegrador.controller.Controller;


public class AdminView extends javax.swing.JFrame {

    private Controller control;

    public AdminView(Controller control) {
        initComponents();
        this.control=control;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRH = new javax.swing.JButton();
        btnMesa = new javax.swing.JButton();
        btnComer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRH.setText("Vista RRHH");

        btnMesa.setText("Vista Mesa Ayuda");

        btnComer.setText("Vista Comercial");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(btnRH)
                .addGap(85, 85, 85)
                .addComponent(btnMesa)
                .addGap(80, 80, 80)
                .addComponent(btnComer)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRH)
                    .addComponent(btnMesa)
                    .addComponent(btnComer))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComer;
    private javax.swing.JButton btnMesa;
    private javax.swing.JButton btnRH;
    // End of variables declaration//GEN-END:variables
}
